inputs:
  command:
    description: "Can be either update (partial) or scrape (all)"
    required: true

runs:
  using: "composite"
  steps:
    - id: install
      name: Install Python, pipenv and Pipfile packages
      uses: palewire/install-python-pipenv-pipfile@v2
      with:
        python-version: 3.9

    - id: make
      name: Run make command
      run: make -f ./usda/Makefile ${{ inputs.command }}
      shell: bash

    - id: commit
      name: Commit results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "actions@github.com"
        git config pull.rebase false
        git status
        git pull origin $GITHUB_REF
        git add usda/
        git commit -m "USDA ${{ inputs.module }}" && git push || true
      shell: bash
