name: USDA Update
on:
  schedule:
    - cron: '1 */4 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: run
        name: Run
        uses: ./.github/actions/usda
        with:
          command: update
